---
- name: Download Hugo Archive
  ansible.builtin.get_url:
    url: "https://github.com/gohugoio/hugo/releases/download/v{{ hugo_version }}/hugo_{% if hugo_extended %}extended_{% endif %}{{ hugo_version }}_{{ hugo_arch }}.tar.gz"
    dest: /tmp/hugo.tar.gz
    mode: u=rw,g=rw,o=rw

- name: Extract Archive
  ansible.builtin.unarchive:
    src: /tmp/hugo.tar.gz
    dest: /tmp/
    remote_src: true

- name: Add Extracted Executable to Path
  become: true
  ansible.builtin.copy:
    src: /tmp/hugo
    dest: /usr/local/bin/hugo
    remote_src: true
    mode: u=rwx,g=rx,o=rx
