---
- name: Check if Hugo is installed
  ansible.builtin.shell: hugo version
  failed_when: false
  changed_when: false
  register: __hugo_output__

- import_tasks: uninstall.yml
  when:
    - hugo_version not in __hugo_output__.stdout
    - __hugo_output__.rc == 0

- import_tasks: install.yml
  when: hugo_version not in __hugo_output__.stdout

- import_tasks: shell_completion.yml
  when:
    - hugo_shell is defined
